/**
 * emit.js - write a runnable MCP server for the compiled app.
 *
 * The output is the artifact: readable, diffable, version-controllable code
 * plus the tests the compiler ran. A generated server is a thing you can
 * review; a computer-use session is an event that happened once.
 */
import { mkdirSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'

export function emit(tools, { app, outDir = 'generated', target }) {
  const dir = join(outDir, app)
  mkdirSync(dir, { recursive: true })

  writeFileSync(join(dir, 'tools.json'), JSON.stringify({ app, target, generatedBy: 'apic', tools }, null, 2))
  writeFileSync(join(dir, 'server.js'), server(app, target))
  writeFileSync(join(dir, 'README.md'), readme(app, target, tools, resolve(dir, 'server.js')))
  return { dir, count: tools.length }
}

const server = (app, target) => `#!/usr/bin/env node
// GENERATED BY apic - do not edit by hand.
// Compiled from ${target} by exploring the UI. The app's own API was never read.
import { Server } from '@modelcontextprotocol/sdk/server/index.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { CallToolRequestSchema, ListToolsRequestSchema } from '@modelcontextprotocol/sdk/types.js'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { replay } from '../../src/replay.js'
import { replayRead } from '../../src/replay-read.js'

const here = dirname(fileURLToPath(import.meta.url))
const { tools } = JSON.parse(readFileSync(join(here, 'tools.json'), 'utf8'))

const server = new Server({ name: 'apic-${app}', version: '0.1.0' }, { capabilities: { tools: {} } })

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: tools.filter((tool) => tool.verification?.verified !== false)
    .map(({ name, description, inputSchema }) => ({ name, description, inputSchema })),
}))

server.setRequestHandler(CallToolRequestSchema, async (req) => {
  const tool = tools.find((t) => t.name === req.params.name)
  if (!tool) throw new Error(\`unknown tool: \${req.params.name}\`)
  // Two kinds of compiled tool, two executors. A read returns JSON rows shaped
  // by the tool's rowSchema; a write returns the state change it observed.
  const run = tool.kind === 'read' ? replayRead : replay
  const result = await run(tool, req.params.arguments || {})
  return { content: [{ type: 'text', text: JSON.stringify(result) }] }
})

await server.connect(new StdioServerTransport())
`

const readme = (app, target, tools, serverPath) => `# apic-${app}

Generated by [apic](https://github.com/brwbo/apic) from \`${target}\`.

**Nothing here was written by a human.** The tools below were discovered by
exploring the app's UI, verified by executing them against live state, and
emitted as an MCP server. The app's own API was never read.

## Tools

${tools.map((t) => `### \`${t.name}\`\n\n${t.description}\n\n\`\`\`json\n${JSON.stringify(t.inputSchema, null, 2)}\n\`\`\`\n\n<details><summary>evidence</summary>\n\n\`\`\`json\n${JSON.stringify(t.provenance.evidence, null, 2)}\n\`\`\`\n</details>`).join('\n\n')}

## Run

\`\`\`bash
node server.js
\`\`\`

## Connect an agent

The generated server uses MCP over stdio. Add it to either client:

\`\`\`bash
# Claude Code
claude mcp add --transport stdio apic-${app} -- node ${serverPath}
\`\`\`

\`\`\`toml
# ~/.codex/config.toml
[mcp_servers.apic-${app}]
command = "node"
args = ["${serverPath}"]
\`\`\`
`
